version: "3"
services:
  r_datascience_debug:
    image: mrds_base:latest
    # restart: unless-stopped
    ports:
      - "8787:8787" #rstudio
    volumes:
      - ./volume:/home/user/.rstudio/monitored/user-settings/
    environment:
      - DISPLAY=$DISPLAY
    tty: true
