on:
  push:
    branches:
      - main
    #   - dev
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta Base
        id: meta-base
        uses: docker/metadata-action@v4
        with:
          images: mikeintosh/mrds_base_j
          tags: |
            latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=mrds_base_j
            org.opencontainers.image.description=Base image for R Datascience
            org.label-schema.url=https://github.com/MIKEINTOSHSYSTEMS/MIKEINTOSH_RDataSystems
            org.label-schema.vsc-url=https://github.com/MIKEINTOSHSYSTEMS/MIKEINTOSH_RDataSystems
      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfiles/mrds_base_j.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          cache-from: mikeintosh/mrds_base_j:latest
      - name: Docker meta Headless
        id: meta-headless
        uses: docker/metadata-action@v4
        with:
          images: mikeintosh/mrds_headless_j
          tags: |
            latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=mrds_headless_j
            org.opencontainers.image.description=Image with a lot of pre-installed packages for R Datascience
            org.label-schema.url=https://github.com/MIKEINTOSHSYSTEMS/MIKEINTOSH_RDataSystems
            org.label-schema.vsc-url=https://github.com/MIKEINTOSHSYSTEMS/MIKEINTOSH_RDataSystems
      - name: Build and push headless image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfiles/mrds_headless_j.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-headless.outputs.tags }}
          labels: ${{ steps.meta-headless.outputs.labels }}
          cache-from: mikeintosh/mrds_headless_j:latest
          build-args: |
            GITHUB_PAT=${{ secrets.PAT }}
      - name: Docker meta RStudio
        id: meta-rstudio
        uses: docker/metadata-action@v4
        with:
          images: mikeintosh/mrds_rstudio_j
          tags: |
            latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=mrds_rstudio_j
            org.opencontainers.image.description=Image with a lot of pre-installed packages for R Datascience
            org.label-schema.url=https://github.com/MIKEINTOSHSYSTEMS/MIKEINTOSH_RDataSystems
            org.label-schema.vsc-url=https://github.com/MIKEINTOSHSYSTEMS/MIKEINTOSH_RDataSystems
      - name: Build and push RStudio image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfiles/mrds_rstudio_j.dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-rstudio.outputs.tags }}
          labels: ${{ steps.meta-rstudio.outputs.labels }}
          cache-from: mikeintosh/mrds_rstudio_j:latest
