name: Generate changelog
on:
  release:
    types: [created, edited]
  # push:
  #   branches: [main, master, dev]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@v1.2.5
      with:
        # REPO_NAME: '<YourUserName>/<YourRepoName>'
        ACCESS_TOKEN: ${{secrets.PAT}}
        # PATH: 'CHANGELOG.md'
        # COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        BRANCH: 'autochangelog'
        PULL_REQUEST: 'dev'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
